version: "3"
services:
  doctolib:
    image: buildkite/puppeteer
    working_dir: /app
    env_file:
      - config.env
    volumes:
      - ./:/app
    command: >
      bash -c "npm install
      && node index.js"
    logging:
      options:
        max-size: "2m"
        max-file: "10"
